
# supabase/config.toml
project_id = "knoevkvjyuchhcmzsdpq"
services = [
  {id = "gotrue", name = "GoTrue", port = 9999},
  {id = "storage", name = "Storage", port = 5000},
]

[api]
port = 54321
types = "types"
auto_update_types = true

# Twilio Webhook functions should not require auth
[functions.twilio-voice-webhook]
verify_jwt = false

[functions.twilio-task-assignment]
verify_jwt = false
