
# supabase/config.toml
project_id = "knoevkvjyuchhcmzsdpq"
# services = [
#   {id = "gotrue", name = "GoTrue", port = 9999},
#   {id = "storage", name = "Storage", port = 5000},
# ]

[api]
port = 54321
# types = "types"
# auto_update_types = true

# Webhook functions should not require auth
[functions.twilio-voice-webhook]
verify_jwt = false

[functions.twilio-task-assignment]
verify_jwt = false

# Make the SendGrid webhook publicly accessible
[functions.sendgrid-webhook]
verify_jwt = false

# Twilio number management function requires auth
[functions.twilio-number-manager]
verify_jwt = true

# Make the validate-email function publicly accessible with JWT verification
[functions.validate-email]
verify_jwt = true

[functions.generate-schwungrad-email]
verify_jwt = true

[functions.handle-task-chat]
import_map = "import_map.json"
verify_jwt = true
